// Zero hardcoded notification templates. Ever.
// Every message a student receives outside of direct tutoring
// is generated by this agent from scratch with full context.

import { callBrain } from './llama_server';
import { db } from '../db/client';
import { logger } from '../middleware/logger';

const NOTIFICATION_PERSONA = `You are Wax, a warm Nigerian AI tutor sending a WhatsApp message to a student.

Rules for notifications:
- Sound like a real person who knows this student, not a system message
- Use their name if you know it
- Reference specific things from their learning history (topics, analogies, breakthroughs)
- Match their language style (if they use Pidgin, use some Pidgin)
- Be short — max 3 sentences for most notifications, max 6 for exam day
- Never start with "Hello!" or "Hi there!" or any generic greeting
- Never use "Certainly!", "Of course!", "Great job!" as opening words
- Never mention "algorithm", "AI", "system", "database", or "reminder"
- Sound like a friend who happens to also be their tutor
- For exam messages: confidence, not pressure
- For review messages: curiosity, not obligation
- For re-engagement: warmth, not guilt`;

async function getStudentContext(studentId: string): Promise<string> {
  const result = await db.query(
    `SELECT
       memory_blocks,
       study_streak,
       last_study_date,
       exam_targets,
       concept_progress,
       error_diary,
       cultural_context
     FROM student_profiles WHERE student_id = $1`,
    [studentId]
  );

  if (result.rows.length === 0) return 'New student — no history available.';

  const row = result.rows[0];

  // Get last 3 conversation turns for recent context
  const recentTurns = await db.query(
    `SELECT student_message, tutor_response, topic, timestamp
     FROM conversation_turns WHERE student_id = $1
     ORDER BY timestamp DESC LIMIT 3`,
    [studentId]
  );

  const memBlocks = row.memory_blocks || {};
  const examTargets = row.exam_targets || [];
  const errorDiary = (row.error_diary || []).slice(-3);
  const conceptProgress = row.concept_progress || {};

  // Find strongest and weakest concepts
  const concepts = Object.entries(conceptProgress) as [string, { masteryLevel: number }][];
  concepts.sort((a, b) => b[1].masteryLevel - a[1].masteryLevel);
  const strongest = concepts.slice(0, 2).map(([k]) => k);
  const weakest = concepts.filter(([, v]) => v.masteryLevel < 0.4).slice(0, 2).map(([k]) => k);

  return `Student info:
${memBlocks.humanProfile || 'No profile yet'}
Study streak: ${row.study_streak} days
Last studied: ${row.last_study_date || 'never'}
Exam targets: ${JSON.stringify(examTargets.slice(0, 2))}
Strongest concepts: ${strongest.join(', ') || 'none recorded'}
Weakest concepts: ${weakest.join(', ') || 'none recorded'}
Recent error patterns: ${errorDiary.map((e: { concept: string }) => e.concept).join(', ') || 'none'}
Recent conversation:
${recentTurns.rows.map((t: Record<string, unknown>) => `Student: "${(t.student_message as string)?.slice(0, 80)}" | Topic: ${t.topic || 'general'}`).join('\n')}`;
}

export async function generatePersonalizedNotification(
  studentId: string,
  type: string,
  contextSummary: string
): Promise<string | null> {
  const studentContext = await getStudentContext(studentId);

  const typeDescriptions: Record<string, string> = {
    exam_today: 'The student has an exam TODAY. Send a calm, specific confidence message. Reference what they are strong in. Wish them well in a personal way.',
    exam_tomorrow: 'The student has an exam TOMORROW. Offer one last review of their weakest area. Also gently remind them to sleep well and eat before the exam.',
    re_engagement: 'The student has not studied for 3+ days. Reach out warmly. Ask how they are doing. Reference what we last worked on. No pressure. Pure warmth.',
    spaced_review: 'A concept the student learned earlier is due for review before they forget it. Make the message curious and light, not a chore.',
    streak_milestone: 'The student hit a study streak milestone. Celebrate it specifically — reference what they have accomplished in that streak, not just the number.',
    frustration_recovery: 'The student showed frustration in their last session. Check in on them. Acknowledge that the topic is hard without making them feel bad.',
    shame_recovery: 'The student showed shame indicators in their last session. Reach out gently. Do not mention what happened — just be warm and inviting.',
    study_plan_progress: 'The student completed a week of their study plan. Celebrate the milestone and preview what comes next.',
    weekly_summary: 'End of week. Give a personalized summary of what they learned, how their confidence grew, and what next week holds.',
    breakthrough_celebration: 'The student had a breakthrough — they mastered a concept they previously struggled with. Celebrate this specifically.',
    learning_velocity: 'The student is learning faster than expected. Acknowledge it and suggest an advanced topic they might enjoy.',
    anti_cramming: 'The student is trying to learn too many new concepts 1-2 days before their exam. Gently redirect to revision, not new learning.',
  };

  const typeDescription = typeDescriptions[type] || contextSummary;

  const prompt = `${NOTIFICATION_PERSONA}

STUDENT CONTEXT:
${studentContext}

NOTIFICATION TYPE: ${type}
WHAT THIS MESSAGE SHOULD DO: ${typeDescription}
ADDITIONAL CONTEXT: ${contextSummary}

Write the WhatsApp message now. Do not include quotes or labels. Just the message text.`;

  try {
    const message = await callBrain(prompt, 0.7, 300);
    if (!message || message.length < 10) return null;

    logger.info(`[NotificationAgent] Generated ${type} for ${studentId}: ${message.slice(0, 80)}...`);
    return message.trim();
  } catch (err) {
    logger.error('[NotificationAgent] Generation failed:', err);
    return null;
  }
}

export async function processPendingNotifications(
  sendFn: (studentId: string, message: string) => Promise<void>
): Promise<void> {
  const result = await db.query(
    `SELECT id, student_id, type, content, context
     FROM notification_queue
     WHERE sent = FALSE AND scheduled_at <= NOW()
     ORDER BY priority DESC, scheduled_at ASC
     LIMIT 20`
  );

  for (const row of result.rows) {
    try {
      await sendFn(row.student_id, row.content);

      await db.query(
        `UPDATE notification_queue SET sent = TRUE, sent_at = NOW() WHERE id = $1`,
        [row.id]
      );

      logger.info(`[NotificationAgent] Sent ${row.type} to ${row.student_id}`);
      await new Promise(r => setTimeout(r, 800));
    } catch (err) {
      logger.error(`[NotificationAgent] Send failed for ${row.id}:`, err);
    }
  }
}